"""Render the committed results into a leaderboard you can read without a network.

``ecstasy report`` writes ``results/LEADERBOARD.md`` from ``results/runs.jsonl``. The
markdown is generated, never hand-edited, and committed alongside the data — so it
diffs in a PR, and an agent picking up a task can see what has already been benchmarked
from the repo alone, with no token and no Notion.

Two display rules are enforced here rather than left to whoever writes the table:

* **iRMSD and LRMSD always appear beside DockQ.** DockQ averages fnat with two RMSD
  terms, so a model that has docked nothing still scores off fnat alone — and scores
  *highest* where its geometry is worst. A DockQ column on its own has misled this
  project before, four conclusions' worth.
* **A row whose model code was dirty is marked.** It is a legitimate experiment (the
  MiniFold residx patch is exactly this), but the reader has to be told that the
  recorded commit does not fully describe what ran.
"""
from __future__ import annotations

from pathlib import Path

from ecstasy import results

_REPO_ROOT = Path(__file__).resolve().parents[2]
OUT = _REPO_ROOT / "results" / "LEADERBOARD.md"

#: Contact metrics in the order they are reported.
_CONTACT = ("P@K", "P@K/2", "P@K/5", "AUC")
#: DockQ never travels alone. The order is the reading order: the score, then the two
#: geometry terms that say whether the score means anything.
_STRUCTURE = ("DockQ", "iRMSD", "LRMSD", "Fnat", "TM_mean")


def _fmt(v, nd=3):
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:.{nd}f}"
    return str(v)


def _dirty_models(row) -> list[str]:
    return sorted(n for n, c in (row["provenance"].get("model_code") or {}).items()
                  if c.get("dirty"))


def _flag(row) -> str:
    marks = []
    if _dirty_models(row):
        marks.append("†")
    if row["provenance"].get("ecstasy_dirty"):
        marks.append("‡")
    if not (row.get("coverage") or {}).get("complete", True):
        marks.append("*")
    return "".join(marks)


def _contact_table(rows) -> list[str]:
    head = "| model | variant | n | " + " | ".join(_CONTACT) + " | TFLOPs | code |"
    out = [head, "|" + "---|" * (len(_CONTACT) + 5)]
    for r in rows:
        mean = (r["metrics"].get("mean") or {})
        cells = [_fmt(mean.get(m)) for m in _CONTACT]
        fl = r.get("flops") or {}
        tflops = _fmt(fl["mean"] / 1e12, 1) if fl.get("mean") else "—"
        sha = (r["provenance"].get("ecstasy_sha") or "")[:7]
        out.append(f"| {r['model']['name']}{_flag(r)} | {r['model']['variant']} | "
                   f"{r['n']['evaluated']} | " + " | ".join(cells)
                   + f" | {tflops} | `{sha}` |")
    return out


def _structure_table(rows) -> list[str]:
    rows = [r for r in rows if r.get("structure")]
    if not rows:
        return []
    head = ("| model | variant | n | " + " | ".join(_STRUCTURE)
            + " | acceptable | medium | high |")
    out = ["", "### Structure", "",
           "DockQ is reported with iRMSD and LRMSD because it averages fnat with two "
           "RMSD terms: an unformed interface still scores off fnat alone. A DockQ "
           "figure quoted without its geometry is not interpretable.", "",
           head, "|" + "---|" * (len(_STRUCTURE) + 6)]
    for r in rows:
        s = r["structure"]
        mean = s.get("mean") or {}
        cells = [_fmt(mean.get(m)) for m in _STRUCTURE]
        out.append(f"| {r['model']['name']}{_flag(r)} | {r['model']['variant']} | "
                   f"{s.get('n')} | " + " | ".join(cells)
                   + f" | {_fmt(s.get('acceptable_fraction'))} "
                     f"| {_fmt(s.get('medium_fraction'))} "
                     f"| {_fmt(s.get('high_fraction'))} |")
    return out


def render(rows: list[dict] | None = None) -> str:
    rows = results.load() if rows is None else rows
    lines = [
        "# Benchmark leaderboard",
        "",
        "Generated by `ecstasy report` from `results/runs.jsonl`. **Do not edit by "
        "hand** — regenerate it.",
        "",
        "Each row is one published run, keyed by its prediction and scoring "
        "fingerprints. A dependency bump or a metric fix appends a new row rather than "
        "editing an old one, so `git log -p results/runs.jsonl` shows a number moving "
        "and what changed underneath it.",
        "",
    ]
    if not rows:
        lines += ["_Nothing published yet._ Score a run, then "
                  "`ecstasy publish --dataset D --model M`.", ""]
        return "\n".join(lines)

    by_dataset: dict[str, list[dict]] = {}
    for r in rows:
        by_dataset.setdefault(r["dataset"]["name"], []).append(r)

    for name in sorted(by_dataset):
        group = sorted(by_dataset[name],
                       key=lambda r: -( (r["metrics"].get("mean") or {}).get("P@K") or 0))
        ds = group[0]["dataset"]
        lines += [f"## {name}", ""]
        if ds.get("expected_entries"):
            lines.append(f"{ds['expected_entries']} entries · dataset version "
                         f"{ds.get('version')}")
            lines.append("")
        lines += ["### Contacts", ""] + _contact_table(group)
        lines += _structure_table(group)
        lines.append("")

    footnotes = []
    if any(_dirty_models(r) for r in rows):
        models = sorted({m for r in rows for m in _dirty_models(r)})
        footnotes.append(
            f"† model source tree was modified at run time ({', '.join(models)}). This "
            f"is intended for MiniFold — the `residx` patch is applied to its working "
            f"tree and is the difference between the intended chain break and a "
            f"linker-only variant — but it means the recorded commit does not fully "
            f"describe what ran. The modified files are on the row in `runs.jsonl`.")
    if any(r["provenance"].get("ecstasy_dirty") for r in rows):
        footnotes.append("‡ published from a dirty ecstasy tree (`--allow_dirty`): the "
                         "recorded commit does not contain the code that ran.")
    if any(not (r.get("coverage") or {}).get("complete", True) for r in rows):
        footnotes.append("\\* incomplete coverage — the mean is over part of the split.")
    if footnotes:
        lines += ["---", ""] + [f"{f}" for f in footnotes] + [""]
    return "\n".join(lines)


def write(out: Path | None = None) -> Path:
    out = Path(out or OUT)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render())
    return out
