benchmark: mint_seqid30
model: msa_pairformer
data_root: /projects/u6jv/boltz_benchmarking/DATA

model_config:
  env_path: /home/u6jv/harsh.u6jv/ecstasy/envs/.venv-esmfold
  max_msa_depth: 512
  predict_limit: 1
