"""Pull the Notion benchmarking Registry (Checkpoints + Datasets tables) into a gitignored
local cache so scripts can resolve a checkpoint/dataset *name* -> concrete path offline.

Notion is the source of truth; this writes ``registry.local.yaml`` at the repo root (never
committed). Re-run whenever the Registry changes.

  PYTHONPATH=src python scripts/mentos-perf-benchmarking/notion_pull.py

Reads from env / .env (see .env.example):
  NOTION_API_TOKEN                     (required)
  ECSTASY_REGISTRY_DB_CHECKPOINTS      (optional — else discovered from ECSTASY_REGISTRY_PAGE_ID)
  ECSTASY_REGISTRY_DB_DATASETS         (optional — else discovered)
  ECSTASY_REGISTRY_PAGE_ID             (used for discovery if DB ids are absent)
"""
from __future__ import annotations

import sys
from pathlib import Path

import requests
import yaml

from ecstasy.config import env_value

_REPO_ROOT = Path(__file__).resolve().parents[2]
_OUT = _REPO_ROOT / "registry.local.yaml"
_NV = "2022-06-28"


def _headers() -> dict:
    tok = env_value("NOTION_API_TOKEN")
    if not tok:
        sys.exit("NOTION_API_TOKEN not set (env or .env)")
    return {"Authorization": f"Bearer {tok}", "Notion-Version": _NV}


def _txt(prop) -> str:
    return "".join(x.get("plain_text", "") for x in (prop.get("title") or prop.get("rich_text") or []))


def _query_all(db_id: str, headers: dict) -> list[dict]:
    rows, cur = [], None
    while True:
        body = {"page_size": 100}
        if cur:
            body["start_cursor"] = cur
        j = requests.post(f"https://api.notion.com/v1/databases/{db_id}/query", headers=headers, json=body).json()
        if "results" not in j:
            sys.exit(f"Notion query failed for {db_id}: {j}")
        rows += j["results"]
        if not j.get("has_more"):
            return rows
        cur = j["next_cursor"]


def _discover_dbs(page_id: str, headers: dict) -> dict[str, str]:
    """Map child-database title -> id for the registry page."""
    out = {}
    j = requests.get(f"https://api.notion.com/v1/blocks/{page_id}/children?page_size=100", headers=headers).json()
    for b in j.get("results", []):
        if b["type"] == "child_database":
            out[b["child_database"]["title"]] = b["id"]
    return out


def main() -> None:
    H = _headers()
    ck_id = env_value("ECSTASY_REGISTRY_DB_CHECKPOINTS")
    ds_id = env_value("ECSTASY_REGISTRY_DB_DATASETS")
    if not (ck_id and ds_id):
        page = env_value("ECSTASY_REGISTRY_PAGE_ID")
        if not page:
            sys.exit("set ECSTASY_REGISTRY_DB_CHECKPOINTS/DATASETS or ECSTASY_REGISTRY_PAGE_ID")
        found = _discover_dbs(page, H)
        ck_id = ck_id or found.get("Checkpoints")
        ds_id = ds_id or found.get("Datasets")
        if not (ck_id and ds_id):
            sys.exit(f"could not find Checkpoints/Datasets DBs on page {page}: {list(found)}")

    checkpoints = {}
    for r in _query_all(ck_id, H):
        p = r["properties"]
        key = _txt(p["key"])
        if not key:
            continue
        checkpoints[key] = {
            "model": (p["model"]["select"] or {}).get("name"),
            "run_id": _txt(p["run_id"]) or None,
            "step": p["step"]["number"],
            "num_recycles": p["num_recycles"]["number"],
            "abs_path": _txt(p["abs_path"]) or None,
            "model_config_path": _txt(p.get("model_config_path", {})) or None,
            "status": (p["status"]["select"] or {}).get("name"),
        }

    datasets = {}
    for r in _query_all(ds_id, H):
        p = r["properties"]
        name = _txt(p["name"])
        if not name:
            continue
        datasets[name] = {
            "index_path": _txt(p["index_path"]) or None,
            "gt_root": _txt(p["gt_root"]) or None,
            "n": p["n"]["number"],
            "split": _txt(p["split"]) or None,
            "contact_bin": p["contact_bin"]["number"],
            "swap_chains": p["swap_chains"]["checkbox"],
        }

    _OUT.write_text(
        "# Auto-generated by scripts/mentos-perf-benchmarking/notion_pull.py — DO NOT EDIT.\n"
        "# Local cache of the Notion benchmarking Registry (the source of truth). Gitignored.\n"
        + yaml.safe_dump({"checkpoints": checkpoints, "datasets": datasets}, sort_keys=True, allow_unicode=True)
    )
    print(f"wrote {_OUT}  ({len(checkpoints)} checkpoints, {len(datasets)} datasets)")


if __name__ == "__main__":
    main()
